services:
  app-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: api
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/event_participation
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      - mysql
      - redis
      - kafka

  app-worker:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: worker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/event_participation
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_KAFKA_CONSUMER_GROUP_ID: participation-worker-group
    depends_on:
      - mysql
      - kafka

  mysql:
    image: mysql:8.4
    container_name: event-participation-mysql
    environment:
      MYSQL_DATABASE: event_participation
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: event-participation-redis
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:4.1.1
    container_name: event-participation-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: >
        INTERNAL://:29092,
        EXTERNAL://:9092,
        CONTROLLER://:9093

      KAFKA_ADVERTISED_LISTENERS: >
        INTERNAL://kafka:29092,
        EXTERNAL://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        INTERNAL:PLAINTEXT,
        EXTERNAL:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: >
        1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

volumes:
  mysql-data: